{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Robot States",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"date\"\r\nfrom(bucket: \"telemetry\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"robot_metrics\")\r\n  |> group(columns: [\"robot_id\"])\r\n  |> last()\r\n  |> keep(columns: [\"_time\", \"robot_id\", \"state\"])\r\n  |> map(fn: (r) => ({ r with _time: date.truncate(t: r._time, unit: 1s) }))\r\n  |> pivot(\r\n    rowKey: [\"_time\"],\r\n    columnKey: [\"robot_id\"],\r\n    valueColumn: \"state\"\r\n  )\r\n  |> rename(columns: {_time: \"time\"})\r\n"
    }
   ]
  },
  {
   "title": "Active Robots",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"robot_metrics\")\r\n  |> group(columns: [\"robot_id\"])\r\n  |> last()\r\n  |> filter(fn: (r) => r.state == \"active\")\r\n  |> group()\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Battery State of Charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"robot_metrics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"battery\")\r\n  |> filter(fn: (r) => r[\"robot_id\"] == \"robot_1\")"
    }
   ]
  }
 ]
}