apiVersion: 1

datasources:
  - name: telemetry
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: robotics
      defaultBucket: telemetry
    secureJsonData:
      token: secret-token
